version: '3.1'
services:
  crawler:
    depends_on:
    - db
    build: ./
    volumes:
      - .:/usr/app/src
    tty: true
    environment:
      DATABASE_URL: postgres://appuser@localhost/appdb
    command: python3 ./main.py 
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=apppass
      - POSTGRES_DB=appdb
    ports:
      - '5440:5432'
    volumes:
      - appdb:/var/lib/postgresql/appdata
volumes:
  appdb: